# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grid_layout = QtWidgets.QGridLayout(self.centralwidget)
        self.grid_layout.setObjectName("grid_layout")
        self.predicted_letter = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(100)
        self.predicted_letter.setFont(font)
        self.predicted_letter.setFrameShape(QtWidgets.QFrame.Box)
        self.predicted_letter.setText("")
        self.predicted_letter.setObjectName("predicted_letter")
        self.grid_layout.addWidget(self.predicted_letter, 0, 1, 1, 1)
        self.asl_label = QtWidgets.QLabel(self.centralwidget)
        self.asl_label.setObjectName("asl_label")
        self.grid_layout.addWidget(self.asl_label, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.grid_layout.addItem(spacerItem, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_image = QtWidgets.QLabel(self.groupBox)
        self.input_image.setObjectName("input_image")
        self.horizontalLayout.addWidget(self.input_image)
        self.cropped_image = QtWidgets.QLabel(self.groupBox)
        self.cropped_image.setObjectName("cropped_image")
        self.horizontalLayout.addWidget(self.cropped_image)
        self.grid_layout.addWidget(self.groupBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Capture"))
        self.asl_label.setText(_translate("MainWindow", "TextLabel"))
        self.input_image.setText(_translate("MainWindow", "TextLabel"))
        self.cropped_image.setText(_translate("MainWindow", "TextLabel"))
