# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grid_layout = QtWidgets.QGridLayout(self.centralwidget)
        self.grid_layout.setObjectName("grid_layout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.image_label = QtWidgets.QLabel(self.groupBox_2)
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.numbers = QtWidgets.QLCDNumber(self.groupBox_2)
        self.numbers.setObjectName("numbers")
        self.gridLayout.addWidget(self.numbers, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.clear_button = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 2, 0, 1, 1)
        self.pen_size = QtWidgets.QSlider(self.groupBox_2)
        self.pen_size.setMinimum(1)
        self.pen_size.setMaximum(30)
        self.pen_size.setProperty("value", 10)
        self.pen_size.setOrientation(QtCore.Qt.Horizontal)
        self.pen_size.setObjectName("pen_size")
        self.gridLayout.addWidget(self.pen_size, 3, 1, 1, 1)
        self.proc_type = QtWidgets.QComboBox(self.groupBox_2)
        self.proc_type.setObjectName("proc_type")
        self.proc_type.addItem("")
        self.proc_type.addItem("")
        self.gridLayout.addWidget(self.proc_type, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.grid_layout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image"))
        self.image_label.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Pen Size"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        self.proc_type.setItemText(0, _translate("MainWindow", "Bounding Box"))
        self.proc_type.setItemText(1, _translate("MainWindow", "Center Mass"))
        self.label_2.setText(_translate("MainWindow", "Image Processing"))
