# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QGridLayout(self.centralwidget)
        self.main_layout.setObjectName("main_layout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.main_layout.addItem(spacerItem, 0, 2, 1, 1)
        self.controls = QtWidgets.QGroupBox(self.centralwidget)
        self.controls.setObjectName("controls")
        self.gridLayout = QtWidgets.QGridLayout(self.controls)
        self.gridLayout.setObjectName("gridLayout")
        self.image_label = QtWidgets.QLabel(self.controls)
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 0, 0, 1, 1)
        self.clear_button = QtWidgets.QPushButton(self.controls)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 2, 0, 1, 1)
        self.pen_size = QtWidgets.QSlider(self.controls)
        self.pen_size.setMinimum(1)
        self.pen_size.setMaximum(30)
        self.pen_size.setProperty("value", 10)
        self.pen_size.setOrientation(QtCore.Qt.Horizontal)
        self.pen_size.setObjectName("pen_size")
        self.gridLayout.addWidget(self.pen_size, 3, 1, 1, 1)
        self.numbers = QtWidgets.QLCDNumber(self.controls)
        self.numbers.setObjectName("numbers")
        self.gridLayout.addWidget(self.numbers, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.controls)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.controls)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.proc_type = QtWidgets.QComboBox(self.controls)
        self.proc_type.setObjectName("proc_type")
        self.proc_type.addItem("")
        self.proc_type.addItem("")
        self.gridLayout.addWidget(self.proc_type, 4, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.main_layout.addWidget(self.controls, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.main_layout.addItem(spacerItem1, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.proc_type.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sketch Digits"))
        self.controls.setTitle(_translate("MainWindow", "Image"))
        self.image_label.setText(_translate("MainWindow", "TextLabel"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        self.label.setText(_translate("MainWindow", "Pen Size"))
        self.label_2.setText(_translate("MainWindow", "Image Processing"))
        self.proc_type.setItemText(0, _translate("MainWindow", "Bounding Box"))
        self.proc_type.setItemText(1, _translate("MainWindow", "Center Mass"))
